### PR TITLE
fix/636-json-editor

### LINKED ISSUE #636: [Admin UI] Json value - json editor stores \n characters when format is applied
**Describe the bug**
When formatting Json feature value in Admin UI, it adds \n characters which should be stripped out when sent to the server. 

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

### PR DESCRIPTION
**Pull request by IrinaSouth**
# Description

Ensure when JSON feature values are set, they do not contain characters like \n due to formatting

Fixes #636

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart [hunk 1]
```diff
@@ -36,7 +38,7 @@ class _EditJsonValueContainerState extends State<EditJsonValueContainer> {
     final valueSource = widget.rolloutStrategy != null
         ? widget.rolloutStrategy!.value
         : widget.strBloc.featureValue.valueJson;
-    tec.text = (valueSource ?? '').toString();
+    tec.text = (const JsonEncoder.withIndent('  ').convert(json.decode(valueSource)) ?? '').toString();
```
Comment (rvowles) [inline admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart:41]: i would put a try/catch in here just in case? then you can set it to empty and editing the page won't blow up.

File: admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart [hunk 2]
```diff
@@ -125,7 +127,7 @@ class _EditJsonValueContainerState extends State<EditJsonValueContainer> {
   }
 
   void _valueChanged() {
-    final replacementValue = tec.text.isEmpty ? null : tec.text.trim();
+    final replacementValue = tec.text.isEmpty ? null : json.encode(json.decode(tec.text.trim())).toString();
```
Comment (rvowles) [inline admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart:130]: an empty string works here??

**Review by rvowles — APPROVED** [review]
